// <auto-generated/>
// This file was generated by XrmTools FetchXmlCodeGenerator.
namespace XrmGenTestClassic;
internal static class FetchXmlArtifact
{
    public const string Xml = @"<?xml version=""1.0"" encoding=""utf-8"" ?>
<fetch xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xsi:noNamespaceSchemaLocation="".xrmtools/schemas/Fetch.xsd"">
	<entity name=""contact"">
		<attribute name=""fullname"" />
		<attribute name=""telephone1""/>
		<attribute name=""bpg_address1_fulladdress""/>
		<filter>
			<condition attribute=""fullname"" operator=""not-begin-with"" value=""Logic""/>
			<condition attribute=""fullname"" operator=""neq"" value="". .""/>
			<condition attribute=""telephone1"" operator=""begins-with"" value=""+32""/>
		</filter>
	</entity>
</fetch>";
    public const string ModelJson = @"{
  ""Version"": null,
  ""Distinct"": null,
  ""NoLock"": null,
  ""ReturnTotalRecordCount"": null,
  ""Aggregate"": null,
  ""Count"": null,
  ""Page"": null,
  ""Top"": null,
  ""PagingCookie"": null,
  ""OutputFormat"": null,
  ""Mapping"": null,
  ""MinActiveRowVersion"": null,
  ""Entity"": {
    ""EnablePrefiltering"": null,
    ""PrefilterParameterName"": null,
    ""AllAttributes"": null,
    ""Name"": ""contact"",
    ""Alias"": null,
    ""Attributes"": [
      {
        ""Name"": ""fullname"",
        ""Alias"": null,
        ""Aggregate"": null,
        ""GroupBy"": null,
        ""DateGrouping"": null,
        ""Distinct"": null,
        ""UserTimeZone"": null,
        ""Extras"": {}
      },
      {
        ""Name"": ""telephone1"",
        ""Alias"": null,
        ""Aggregate"": null,
        ""GroupBy"": null,
        ""DateGrouping"": null,
        ""Distinct"": null,
        ""UserTimeZone"": null,
        ""Extras"": {}
      },
      {
        ""Name"": ""bpg_address1_fulladdress"",
        ""Alias"": null,
        ""Aggregate"": null,
        ""GroupBy"": null,
        ""DateGrouping"": null,
        ""Distinct"": null,
        ""UserTimeZone"": null,
        ""Extras"": {}
      }
    ],
    ""Orders"": [],
    ""Filters"": [
      {
        ""Type"": 0,
        ""Conditions"": [
          {
            ""Attribute"": ""fullname"",
            ""EntityAlias"": null,
            ""Operator"": ""not-begin-with"",
            ""ValueIsNull"": null,
            ""Values"": [
              {
                ""Text"": ""Logic"",
                ""Uitype"": null,
                ""Uiname"": null,
                ""Typed"": ""Logic"",
                ""TypeHint"": null,
                ""Extras"": {}
              }
            ],
            ""Extras"": {}
          },
          {
            ""Attribute"": ""fullname"",
            ""EntityAlias"": null,
            ""Operator"": ""neq"",
            ""ValueIsNull"": null,
            ""Values"": [
              {
                ""Text"": "". ."",
                ""Uitype"": null,
                ""Uiname"": null,
                ""Typed"": "". ."",
                ""TypeHint"": null,
                ""Extras"": {}
              }
            ],
            ""Extras"": {}
          },
          {
            ""Attribute"": ""telephone1"",
            ""EntityAlias"": null,
            ""Operator"": ""begins-with"",
            ""ValueIsNull"": null,
            ""Values"": [
              {
                ""Text"": ""+32"",
                ""Uitype"": null,
                ""Uiname"": null,
                ""Typed"": 32,
                ""TypeHint"": null,
                ""Extras"": {}
              }
            ],
            ""Extras"": {}
          }
        ],
        ""Filters"": [],
        ""Extras"": {}
      }
    ],
    ""Links"": [],
    ""Extras"": {}
  },
  ""Settings"": {},
  ""Extras"": {
    ""xmlns:xsi"": ""http://www.w3.org/2001/XMLSchema-instance"",
    ""xsi:noNamespaceSchemaLocation"": "".xrmtools/schemas/Fetch.xsd""
  }
}";
}
