// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "XrmGen.eba3cd26-ffad-444f-b4ef-771d430bacef";
        public const string Name = "XrmGen";
        public const string Description = @"Power Platform Code Generator";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Reza";
        public const string Tags = "";
    }
}
