// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmGen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidXrmCodeGenPackageString = "9d0b1940-11e7-41cc-a95a-ad5a6ed3c73b";
        public static Guid guidXrmCodeGenPackage = new Guid(guidXrmCodeGenPackageString);

        public const string guidXrmCodeGenUIRuleString = "6b9f081c-67ed-43f3-8434-237387ae4f5d";
        public static Guid guidXrmCodeGenUIRule = new Guid(guidXrmCodeGenUIRuleString);

        public const string guidXrmCodeGenPackageCmdSetString = "15d399a7-b2ae-4f1c-9771-3dae966a7134";
        public static Guid guidXrmCodeGenPackageCmdSet = new Guid(guidXrmCodeGenPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int EntityGeneratorCommandId = 0x0100;
    }
}