// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmTools
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AssetsGuidString = "b11584c1-89bd-47a3-b6a4-05b05dd5fc13";
        public static Guid AssetsGuid = new Guid(AssetsGuidString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ApplyToDataverse = 0x000A;
        public const int Dataverse = 0x0014;
        public const int XrmTools = 0x001E;
    }
}
