// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "XrmTools.eba3cd26-ffad-444f-b4ef-771d430bacef";
        public const string Name = "Xrm Tools";
        public const string Description = @"Xrm Tools is a Visual Studio extension that makes Power Platform development feel native, with IntelliSense for plugins, boilerplate and typed entity generation, and first-class FetchXML support.";
        public const string Language = "en-US";
        public const string Version = "1.5.5";
        public const string Author = "Reza Niroomand";
        public const string Tags = "Power Platform, Dataverse, Power Apps, XRM";
        public const bool IsPreview = false;
    }
}
