// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "XrmTools.eba3cd26-ffad-444f-b4ef-771d430bacef";
        public const string Name = "Xrm Tools";
        public const string Description = @"Xrm Tools is a Visual Studio extension that aims to make Power Platform development feel native within Visual Studio. You will get Intellisense support for your Plugins, generate boiler plate code, typed entities and more right from within Visual Studio. You have full control over code generation using Scriban templates.";
        public const string Language = "en-US";
        public const string Version = "1.4.2";
        public const string Author = "Reza Niroomand";
        public const string Tags = "Power Platform, Dataverse, Power Apps, XRM, Code Generator";
        public const bool IsPreview = false;
    }
}
