// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XrmTools
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string XrmToolsPackageIdString = "9d0b1940-11e7-41cc-a95a-ad5a6ed3c73b";
        public static Guid XrmToolsPackageId = new Guid(XrmToolsPackageIdString);

        public const string SetCustomToolEntitiesCmdUIRuleString = "6b9f081c-67ed-43f3-8434-237387ae4f5d";
        public static Guid SetCustomToolEntitiesCmdUIRule = new Guid(SetCustomToolEntitiesCmdUIRuleString);

        public const string SetCustomToolPluginDefitionCmdUIRuleString = "ee3324f2-0e72-4af6-bcba-ac3af05df4e8";
        public static Guid SetCustomToolPluginDefitionCmdUIRule = new Guid(SetCustomToolPluginDefitionCmdUIRuleString);

        public const string NewProjectItemUIRuleString = "87765b0d-0ab7-4812-9668-a2d621957cf9";
        public static Guid NewProjectItemUIRule = new Guid(NewProjectItemUIRuleString);

        public const string CodeGenerationTemplateCmdUIRuleString = "be4c5f8f-c72b-4442-9b9c-d2b5f7f2b9a0";
        public static Guid CodeGenerationTemplateCmdUIRule = new Guid(CodeGenerationTemplateCmdUIRuleString);

        public const string CSProjOrCodeGenerationTemplateCmdUIRuleString = "f3e2d1c4-2b6e-4f7a-8e2e-5c9f0b6e4d3a";
        public static Guid CSProjOrCodeGenerationTemplateCmdUIRule = new Guid(CSProjOrCodeGenerationTemplateCmdUIRuleString);

        public const string guidEnvironmentSelectorString = "1c9aad2b-53da-44b8-89ad-0e1d49945198";
        public static Guid guidEnvironmentSelector = new Guid(guidEnvironmentSelectorString);

        public const string guidSettingsProviderString = "7d969eb6-a17f-431c-8a6e-fe3ea0a9dee3";
        public static Guid guidSettingsProvider = new Guid(guidSettingsProviderString);

        public const string guidXrmSchemaProviderFactoryString = "b27d7354-9380-4c2e-ba0a-f423e727976e";
        public static Guid guidXrmSchemaProviderFactory = new Guid(guidXrmSchemaProviderFactoryString);

        public const string guidXrmPluginCodeGeneratorString = "6b7af55b-dc3d-4bd7-ac39-3e3b60ef279b";
        public static Guid guidXrmPluginCodeGenerator = new Guid(guidXrmPluginCodeGeneratorString);

        public const string guidXrmEntityCodeGeneratorString = "40f321f1-e206-4643-83d8-a14f3495c4ed";
        public static Guid guidXrmEntityCodeGenerator = new Guid(guidXrmEntityCodeGeneratorString);

        public const string XrmToolsCmdSetIdString = "15d399a7-b2ae-4f1c-9771-3dae966a7134";
        public static Guid XrmToolsCmdSetId = new Guid(XrmToolsCmdSetIdString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int XrmToolsProjectContextMenuGroup = 0x0600;
        public const int XrmToolsSolutionContextMenuGroup = 0x0700;
        public const int XrmToolsContextMenuGroup = 0x0100;
        public const int NewFetchXmlFileCmdId = 0x0200;
        public const int SetCustomToolPluginGeneratorCmdId = 0x0300;
        public const int SetCustomToolEntityGeneratorCmdId = 0x0310;
        public const int ResetCodeGenTemplatesCmdId = 0x0320;
        public const int SetPluginGeneratorTemplateInSolutionCmdId = 0x0800;
        public const int SetPluginGeneratorTemplateInProjectCmdId = 0x0810;
        public const int SetEntityGeneratorTemplateInSolutionCmdId = 0x0820;
        public const int SetEntityGeneratorTemplateInProjectCmdId = 0x0830;
        public const int SetEnvironmentCmdId = 0x0500;
        public const int ManageEnvironmentCmdId = 0x0510;
        public const int ManageEnvironmenGetListCmdId = 0x0511;
        public const int RegisterPluginCmdId = 0x0910;
        public const int XrmToolsToolbar = 0x2000;
        public const int XrmToolsToolbarGroup = 0x2010;
        public const int XrmToolsContextSubMenu = 0x1000;
        public const int XrmToolsContextSubMenuGroup = 0x1010;
    }
}
